version: 2
updates:
- package-ecosystem: github-actions
  directory: "/common-files/"
  schedule:
    interval: daily

- package-ecosystem: github-actions
  directory: "/common-files-maven/"
  schedule:
    interval: daily

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
