name: common-files-sync

on:
  push:
    branches:
      - master
    paths:
      - 'common-files/**'
      - '.github/workflows/common-files-sync.yml'

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Sync
        uses: kbrashears5/github-action-file-sync@v2.2.0
        with:
          REPOSITORIES: |
            s4u/maven-settings-action
            s4u/testing
          FILES: |
            common-files/.
          TOKEN: ${{ secrets.TECH_TOKEN }}
