name: labels-sync

on:
  push:
    branches:
      - master
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labels-sync.yml'

jobs:

  labels_sync:

    strategy:
      fail-fast: false
      matrix:
        repo:
          - s4u/jfatek
          - s4u/maven-settings-action
          - s4u/sitemapxml-maven-plugin
          - s4u/parent
          - s4u/pgpverify-maven-plugin
          - s4u/pgp-keys-map
          - s4u/slf4j-mock
          - s4u/testing

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Sync
        uses: micnncim/action-label-syncer@v1.2.0
        with:
          repository: ${{ matrix.repo }}
          token: ${{ secrets.TECH_TOKEN }}
          prune: false
